### ISSUE TITLE
Lessons page, Basic ML: "Notebook not found".

### ISSUE THREAD

**Issue by ColinLeongUDRI** [practicalAI/practicalAI#166]
**Problem:** Starting from either https://practicalai.me/learn/lessons/ or https://github.com/practicalAI/practicalAI, when attempting to click any of the lessons I see "Notebook not found". 
**Proposed fix:** Possibly "basic_ml" should be added to the path?

![image](https://user-images.githubusercontent.com/46969615/73464761-6983a780-434d-11ea-8105-96a468e2d02e.png)

When I click "authorize with Github" I see the same thing: 
![image](https://user-images.githubusercontent.com/46969615/73465167-f7f82900-434d-11ea-92f8-86b2a0b65b80.png)

The link given then does not work: 
![image](https://user-images.githubusercontent.com/46969615/73465251-1bbb6f00-434e-11ea-985e-26f5d272e292.png)

In the case of the "linear regression" notebook, the non-working link given on the "lessons" page is https://colab.research.google.com/github/practicalAI/practicalAI/blob/master/notebooks/04_Linear_Regression.ipynb

Whereas if you go find it on github directly, it is 
https://colab.research.google.com/github/practicalAI/practicalAI/blob/master/notebooks/basic_ml/04_Linear_Regression.ipynb

**Comment by GokuMohandas** [comment]
Hey @ColinLeongUDRI , thanks for catching this mistake! I've fixed the readme and the links on the website as well https://practicalai.me

**Comment by Sherlock-1** [comment]
sorry,it seemed that it still cannot be opened.....If possible,could you please solve the problem?
